### ISSUE TITLE
Problem with de.vogella.rcp.help.application

### ISSUE THREAD

**Issue by marioja** [vogellacompany/codeexamples-java#5]
I tried the sample from your tutorial and the code from https://github.com/vogellacompany/codeexamples-java/tree/master/de.vogella.rcp.help.application and https://github.com/vogellacompany/codeexamples-java/tree/master/de.vogella.rcp.help.content . The context help does not seem to work.  When I run the application and I have the item Two in the View selected I hit F1 and the context help opens up but:

1.	The text under description in the context.xml file does not appear anywhere
2.	I do not see a link to the gettingstarted/subtopic.html

Here is a screen shot after the F1
![vogella](https://user-images.githubusercontent.com/49068/37059042-52da5c7a-215a-11e8-9dac-3792bcdddd42.png)

**Comment by fapdash** [comment]
Thank you for your contribution. Closing.
