### ISSUE TITLE
Help not working (de.vogella.rcp.help.content)

### ISSUE THREAD

**Issue by bertush** [vogellacompany/codeexamples-java#8]
I followed the tutorial https://www.vogella.com/tutorials/EclipseRCPHelpSystem/article.html. 

However, when I try to open Help I get "PWC6349: Cannot find a java compiler for compilation."

Any suggestions?

**Comment by vogella** [comment]
I saw you report https://github.com/eclipse-equinox/equinox/issues/291#issuecomment-1621108408, the team recently changed the compiler settings, try to find a solution via the ticket.
